---
title: "Week2_Day1_QC"
author: "Kimia Mansoori"
format: html
editor: visual
toc: true
---

```{r}
#| eval: false 
library("Rqc") 
library("fastqcr") 
library("QuasR") 
library("ShortRead") 
library("ggplot2")
library ("tidyverse")
print("All Bioconductor packages loaded successfully!")
```

## Step 1: Visualizing Quality with Rqc

```{r}
#| eval: false 
# Define the path to the directory containing the example fastq files
fastq_dir <- system.file(package="ShortRead", "extdata/E-MTAB-1147")

# Run the QC analysis on ALL .fastq.gz files in that directory
qc_result <- rqc(path = fastq_dir, pattern = ".fastq.gz", openBrowser=FALSE)
```

### **1. Average Read Quality: The Bird’s Eye View**

```{r}
#| eval: false 
#| #Above 30 means a good quality so overall good. With the tail end dropping. 
rqcReadQualityBoxPlot(qc_result) 
```

#### Micro_Challenge 1**: The Bird’s Eye Audit**

```{r}
#| eval: false 
p_avg <- rqcReadQualityBoxPlot (qc_result) + 
  geom_hline (yintercept = 30, color = "green", linetype = "dashed")
p_avg
ggsave("average_quality.png", plot = p_avg)
#Question: Is the median average quality of our library above the Q30 line? Yes. 
```

### **2. Per Cycle Quality: The Diagnostic View**

```{r}
#| eval: false 
rqcCycleQualityBoxPlot(qc_result)
```

#### **Micro-Challenge 2: The Quality Threshold**

```{r}
#| eval: false 
p_qual <- rqcCycleQualityBoxPlot(qc_result) +
  geom_hline(yintercept = 30, color = "green", linetype = "dashed") +
  geom_hline(yintercept = 20, color = "red", linetype = "dashed")
p_qual
ggsave("quality_boxplot.png", plot = p_qual)
```

### **3. Per Cycle Base Content: The “Randomness” Check**

```{r}
#| eval: false 
rqcCycleBaseCallsLinePlot(qc_result)
```

#### **Micro-Challenge 3: The Base Composition Audit**

```{r}
#| eval: false 
p_base<- rqcCycleBaseCallsLinePlot(qc_result)
ggsave("base_content_plot.png", plot =p_base)
# Do the lines stay parallel for the entire read, or do they “wiggle” at the beginning? They wiggle at the beginning
```

### **4. Read Frequency: The “Uniqueness” Check**

```{r}
#| eval: false 
rqcReadFrequencyPlot(qc_result)
```

#### **Micro-Challenge 4: The Frequency Audit**

```{r}
#| eval: false 
p_freq <-rqcReadFrequencyPlot(qc_result)
ggsave("read_frequency.png", plot =p_freq)
```
